/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/Baking-donee.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Baking-donee.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor.geometry} material={materials['Floor-wood']} />
      <mesh geometry={nodes.Wall.geometry} material={materials['wall-paint']} position={[0, 2, 2]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.kEYBOARD.geometry} material={materials['keyboard-color']} position={[-0.26, 0.425, 1.473]} />
      <mesh geometry={nodes.mouse.geometry} material={materials['mouse-color']} position={[-0.328, 0.428, 1.465]} rotation={[Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Desk.geometry} material={materials['Desk-color']} position={[-0.659, 0.179, 1.787]} />
      <mesh geometry={nodes.Drawer.geometry} material={materials['Drawer-color']} position={[-0.774, 0.182, 1.558]} />
      <mesh geometry={nodes['Keyboard-mat'].geometry} material={materials['keyboard-mat']} position={[-0.142, 0.407, 1.464]} />
      <mesh geometry={nodes['pencil-holder'].geometry} material={materials['pencil-holder']} position={[0.241, 0.456, 1.517]} />
      <mesh geometry={nodes.cup.geometry} material={materials['cup-color']} position={[-0.522, 0.437, 1.451]} rotation={[0, -0.873, 0]} />
      <mesh geometry={nodes.Mobile.geometry} material={materials.mobile} position={[-0.505, 0.503, 1.45]} rotation={[-1.474, -0.274, -1.227]} />
      <mesh geometry={nodes.Chair.geometry} material={materials.chair} position={[-0.108, 0.265, 1.226]} rotation={[0, 1.086, 0]} />
      <mesh geometry={nodes['yellow-pencil'].geometry} material={materials['pencil-yellow']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes['speaker-cpu'].geometry} material={materials['cpu-part-color']} position={[-0.79, 0.605, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['cpu-setting'].geometry} material={materials['Material.002']} position={[-0.79, 0.605, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['fan-hold-cpu'].geometry} material={materials['Material.001']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['CPU-fan'].geometry} material={materials['cpu-fan-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes.monitor.geometry} material={materials['Pc-color']} position={[-0.136, 0.413, 1.665]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes['monitor-screen'].geometry} material={materials['monitor-screen']} position={[-0.136, 0.413, 1.665]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes['mobile-screen'].geometry} material={materials['mobile-screen']} position={[-0.505, 0.503, 1.45]} rotation={[-1.474, -0.274, -1.227]} />
      <mesh geometry={nodes['purple-pencil'].geometry} material={materials['purple-pencil']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes['pink-pencil'].geometry} material={materials['pink-pencil']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes['red-pencil001'].geometry} material={materials['red-pencil']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes.Pencils011.geometry} material={materials['Material.003']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes.Object.geometry} material={materials['pencil.001']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes.Pencils014.geometry} material={materials['pencil.002']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes.Pencils015.geometry} material={materials['pencil.001']} position={[0.23, 0.469, 1.509]} rotation={[-0.394, -0.141, -0.008]} />
      <mesh geometry={nodes['board-cpu001'].geometry} material={materials['cpu-part-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['board-cpu002'].geometry} material={materials['cpu-part-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['board-cpu003'].geometry} material={materials['cpu-part-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['CPU-Box002'].geometry} material={materials['cpu-box-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['CPU-GLASS002'].geometry} material={materials['cpu-box-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['CPU-GLASSS'].geometry} material={materials.glass} position={[-0.788, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['board-cpu012'].geometry} material={materials['cpu-light.001']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['board-cpu014'].geometry} material={materials['cpu-light.001']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['speaker-cpu001'].geometry} material={materials['cpu-part-color']} position={[-0.79, 0.605, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['speaker-cpu002'].geometry} material={materials['cpu-part-color']} position={[-0.79, 0.638, 1.459]} rotation={[0, 0.608, -Math.PI / 2]} />
      <mesh geometry={nodes['green-pencil'].geometry} material={materials['green-pencil']} position={[0.221, 0.469, 1.508]} rotation={[-0.349, -0.175, 0.161]} />
      <mesh geometry={nodes.Pencils001.geometry} material={materials['pencil.002']} position={[0.221, 0.469, 1.508]} rotation={[-0.349, -0.175, 0.161]} />
      <mesh geometry={nodes.Books.geometry} material={materials['Book3-pg3']} position={[0.37, 0.425, 1.496]} rotation={[0, -0.385, 0]} />
      <mesh geometry={nodes.Books001.geometry} material={materials['Book3-color']} position={[0.37, 0.425, 1.496]} rotation={[0, -0.385, 0]} />
      <mesh geometry={nodes.Books002.geometry} material={materials['Book-2-color']} position={[0.37, 0.425, 1.496]} rotation={[0, -0.385, 0]} />
      <mesh geometry={nodes.Books003.geometry} material={materials['book2-pg2-color']} position={[0.37, 0.425, 1.496]} rotation={[0, -0.385, 0]} />
      <mesh geometry={nodes.Books004.geometry} material={materials['book-1-red']} position={[0.356, 0.424, 1.525]} rotation={[0, -0.036, 0]} />
      <mesh geometry={nodes.Books005.geometry} material={materials['book-1-pg-color']} position={[0.356, 0.424, 1.525]} rotation={[0, -0.036, 0]} />
      <group position={[0.133, 0.491, 1.665]} rotation={[0, -0.432, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Speaker-color']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Speaker-color']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Speaker-color']} />
      </group>
      <group position={[-0.402, 0.491, 1.665]} rotation={[0, 0.478, 0]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Speaker-color']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Speaker-color']} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials['Speaker-color']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Baking-donee.glb')
